In [15]:
from sklearn.model_selection import KFold, StratifiedKFold
kf=KFold(n_splits=2)
x=['a','b','c','d']
for train, test in kf.split(x):
    print("%s %s" %(train, test))

[2 3] [0 1]
[0 1] [2 3]


In [16]:
kf=KFold(n_splits=4)
for train, test in kf.split(x):
    print("%s %s" %(train, test))

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


In [21]:
import numpy as np
x=np.ones(10)
y=[0,0,0,0,1,1,1,1,1,1]
skf=StratifiedKFold(n_splits=3)

for train, test in skf.split(x,y):
    print("%s %s" %(train, test))

[2 3 6 7 8 9] [0 1 4 5]
[0 1 3 4 5 8 9] [2 6 7]
[0 1 2 4 5 6 7] [3 8 9]


In [28]:
# for time series you shpuld use TimeSeriesSplit
from sklearn.model_selection import TimeSeriesSplit
x=np.array([[1,3,4],[7,6,5],[8,9,7],[8,9,4],[9,4,1]])
times=TimeSeriesSplit(n_splits=3)
for train, test in times.split(x):
    print("%s %s" %(train, test))
# it never uses the future data as the test 

[0 1] [2]
[0 1 2] [3]
[0 1 2 3] [4]
