In [19]:
import pandas as pd
import numpy as np
white_wine=pd.read_csv('../../practice/winequality-white.csv', sep=';')
red_wine=pd.read_csv('../../practice/winequality-red.csv', sep=';')
white_wine.columns=white_wine.columns.str.replace(' ','_')
red_wine.columns=red_wine.columns.str.replace(' ','_')
white_wine['wine_type']=0
red_wine['wine_type']=1
total_wine=pd.concat([white_wine, red_wine])


In [20]:
total_wine

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  wine_type  
0         8.8        6          0  
1         9.5        6          0  
2        10.1        6          0  
3         9.9        6          0  
4         9.9        6          0  
...       ...      ...        ...  
1594     10.5        5          1  
1595     11.2        6          1  
1596     11.0        6          1  
1597     10.2        5          1  
1598     11.0        6          1  

[6497 rows x 13 columns]

In [23]:
# sI use z score method to remove outliers
def outliers_idr(df):
    
    num=df.count(axis=1)
    num_col=num[1]
    
    i=0
    for colu in total_wine:
        mean_df=df[colu].mean()
        std_df=df[colu].std()
        df_out= df[(df[colu] <= 3*std_df+mean_df) & (df[colu] >= (mean_df-3*std_df))]
        df=df_out
        i=i+1
        
    return df_out

total_wine=outliers_idr(total_wine)
total_wine= total_wine.set_index(np.arange(len(total_wine)))



In [24]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_train.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.20382882882882883
Confusion matrix:
[[  16 1365]
 [  49  346]]
              precision    recall  f1-score   support

           0       0.25      0.01      0.02      1381
           1       0.20      0.88      0.33       395

    accuracy                           0.20      1776
   macro avg       0.22      0.44      0.18      1776
weighted avg       0.24      0.20      0.09      1776

cohen_kappa is:  -0.05136889665179867


In [29]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9938063063063063
Confusion matrix:
[[1390    4]
 [   7  375]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1394
           1       0.99      0.98      0.99       382

    accuracy                           0.99      1776
   macro avg       0.99      0.99      0.99      1776
weighted avg       0.99      0.99      0.99      1776

cohen_kappa is:  0.9816041733365977


In [39]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.982545045045045
Confusion matrix:
[[1395   13]
 [  18  350]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1408
           1       0.96      0.95      0.96       368

    accuracy                           0.98      1776
   macro avg       0.98      0.97      0.97      1776
weighted avg       0.98      0.98      0.98      1776

cohen_kappa is:  0.9466039756063498


In [44]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9943693693693694
Confusion matrix:
[[1366    1]
 [   9  400]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1367
           1       1.00      0.98      0.99       409

    accuracy                           0.99      1776
   macro avg       1.00      0.99      0.99      1776
weighted avg       0.99      0.99      0.99      1776

cohen_kappa is:  0.9840078087996672


In [64]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model=LinearDiscriminantAnalysis()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9966216216216216
Confusion matrix:
[[1382    2]
 [   4  388]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1384
           1       0.99      0.99      0.99       392

    accuracy                           1.00      1776
   macro avg       1.00      0.99      1.00      1776
weighted avg       1.00      1.00      1.00      1776

cohen_kappa is:  0.990161318915086


In [71]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9859234234234234
Confusion matrix:
[[1410   10]
 [  15  341]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1420
           1       0.97      0.96      0.96       356

    accuracy                           0.99      1776
   macro avg       0.98      0.98      0.98      1776
weighted avg       0.99      0.99      0.99      1776

cohen_kappa is:  0.955852523565207


In [82]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9926801801801802
Confusion matrix:
[[1365    5]
 [   8  398]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1370
           1       0.99      0.98      0.98       406

    accuracy                           0.99      1776
   macro avg       0.99      0.99      0.99      1776
weighted avg       0.99      0.99      0.99      1776

cohen_kappa is:  0.9791915266396767


/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [89]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
model=SVC()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9960585585585585
Confusion matrix:
[[1417    3]
 [   4  352]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1420
           1       0.99      0.99      0.99       356

    accuracy                           1.00      1776
   macro avg       0.99      0.99      0.99      1776
weighted avg       1.00      1.00      1.00      1776

cohen_kappa is:  0.9876907966129889


In [92]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9938063063063063
Confusion matrix:
[[1393    5]
 [   6  372]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1398
           1       0.99      0.98      0.99       378

    accuracy                           0.99      1776
   macro avg       0.99      0.99      0.99      1776
weighted avg       0.99      0.99      0.99      1776

cohen_kappa is:  0.9814976872109014
