In [132]:
#This is a program to predit quality of wines (white+red wines). Here, I did not do anything with outliers
import pandas as pd
import numpy as np
white_wine=pd.read_csv('../../practice/winequality-white.csv', sep=';')
red_wine=pd.read_csv('../../practice/winequality-red.csv', sep=';')

In [133]:
# replace space with underline
white_wine.columns=white_wine.columns.str.replace(' ','_')
red_wine.columns=red_wine.columns.str.replace(' ','_')
#add a new column
red_wine['wine_type']='r'
white_wine['wine_type']='w'
red_wine

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality wine_type  
0         9.4        5         r  
1         9.8        5         r  
2         9.8        5         r  
3         9.8        6         r  
4         9.4        5         r  
...       ...      ...       ...  
1594     10.5        5         r  
1595     11.2        6         r  
1596     11.0        6         r  
1597     10.2        5         r  
1598     11.0        6         r  

[1599 rows x 13 columns]

In [134]:
#add a new column
red_wine['quality_label']=red_wine['quality'].apply(lambda x: 'low' if x <= 5 else 'medium' if x <= 7 else 'high')
red_wine['quality_label']=pd.Categorical(red_wine['quality_label'], categories=['low','high','medium'])
white_wine['quality_label']=white_wine['quality'].apply(lambda x: 'low' if x <= 5 else 'medium' if x <= 7 else 'high')
white_wine['quality_label']=pd.Categorical(white_wine['quality_label'], categories=['low','high','medium'])

In [135]:
#merge two files
total_wine=white_wine.append(red_wine)
total_wine= total_wine.set_index(np.arange(len(total_wine)))
total_wine

/var/folders/nm/btrww2_94pncl34mb0yt49j80000gn/T/ipykernel_63850/508466892.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  total_wine=white_wine.append(red_wine)


fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6492            6.2             0.600         0.08             2.0      0.090   
6493            5.9             0.550         0.10             2.2      0.062   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6493                 39.0                  51.0  0.99512  3.52       0.76   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality wine_type quality_label  
0         8.8        6         w        medium  
1         9.5        6         w        medium  
2        10.1        6         w        medium  
3         9.9        6         w        medium  
4         9.9        6         w        medium  
...       ...      ...       ...           ...  
6492     10.5        5         r           low  
6493     11.2        6         r        medium  
6494     11.0        6         r        medium  
6495     10.2        5         r           low  
6496     11.0        6         r        medium  

[6497 rows x 14 columns]

In [136]:
#encoding
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
#le0=OneHotEncoder(sparse=False)
#total_wine['wine_type']=le0.fit_transform(total_wine[['wine_type']])
#le0.inverse_transform(total_wine['wine_type'].unique()) ####?

total_wine['wine_type']=total_wine['wine_type'].apply(lambda x: 0 if x== 'w' else 1)
le1=LabelEncoder()
total_wine['quality_label']=le1.fit_transform(total_wine['quality_label'])
print(le1.inverse_transform(total_wine['quality_label'].unique())) ###???

['medium' 'low' 'high']


In [137]:
total_wine['quality_label'].value_counts()

2    3915
1    2384
0     198
Name: quality_label, dtype: int64

In [138]:
# ML for quality of wine Decision tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report



model=DecisionTreeClassifier()
x=total_wine.drop(columns=['quality_label', 'quality'])
y=total_wine['quality_label']
scale=MinMaxScaler()
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=42)
x_train_n=scale.fit_transform(x_train)
x_train_n=pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n=scale.fit_transform(x_test)
x_test_n=pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n,y_train)
predict=model.predict(x_test_n)
score=accuracy_score(y_test, predict)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, predict))
print(classification_report(y_test,predict))
cohen=cohen_kappa_score(y_test, predict)
print('cohen_kappa is: ', cohen)

accuracy is:  0.5856410256410256
Confusion matrix:
[[  8  12  34]
 [ 13 467 229]
 [ 70 450 667]]
              precision    recall  f1-score   support

           0       0.09      0.15      0.11        54
           1       0.50      0.66      0.57       709
           2       0.72      0.56      0.63      1187

    accuracy                           0.59      1950
   macro avg       0.44      0.46      0.44      1950
weighted avg       0.62      0.59      0.59      1950

cohen_kappa is:  0.22575509271430427


In [139]:
# ML for quality of wine  RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report



model= RandomForestClassifier()
x=total_wine.drop(columns=['quality_label', 'quality'])
y=total_wine['quality_label']
scale=MinMaxScaler()
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)
x_train_n=scale.fit_transform(x_train)
x_train_n=pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n=scale.fit_transform(x_test)
x_test_n=pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n,y_train)
predict=model.predict(x_test_n)
score=accuracy_score(y_test, predict)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, predict))
print(classification_report(y_test,predict))
cohen=cohen_kappa_score(y_test, predict)
print('cohen_kappa is: ', cohen)

accuracy is:  0.6317948717948718
Confusion matrix:
[[  0   9  49]
 [  0 547 188]
 [  0 472 685]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        58
           1       0.53      0.74      0.62       735
           2       0.74      0.59      0.66      1157

    accuracy                           0.63      1950
   macro avg       0.43      0.45      0.43      1950
weighted avg       0.64      0.63      0.62      1950

cohen_kappa is:  0.2929380668085403


/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [140]:
# ML for quality of wine  LinearDiscriminantAnalysis

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report



model= LinearDiscriminantAnalysis()
x=total_wine.drop(columns=['quality_label', 'quality'])
y=total_wine['quality_label']
scale=MinMaxScaler()
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)
x_train_n=scale.fit_transform(x_train)
x_train_n=pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n=scale.fit_transform(x_test)
x_test_n=pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n,y_train)
predict=model.predict(x_test_n)
score=accuracy_score(y_test, predict)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, predict))
print(classification_report(y_test,predict))
cohen=cohen_kappa_score(y_test, predict)
print('cohen_kappa is: ', cohen)

accuracy is:  0.5728205128205128
Confusion matrix:
[[  0  22  36]
 [  1 676  58]
 [  1 715 441]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        58
           1       0.48      0.92      0.63       735
           2       0.82      0.38      0.52      1157

    accuracy                           0.57      1950
   macro avg       0.43      0.43      0.38      1950
weighted avg       0.67      0.57      0.55      1950

cohen_kappa is:  0.24266866340238924


In [141]:
x_train_n['wine_type'].value_counts()

0.0    3411
1.0    1136
Name: wine_type, dtype: int64

In [142]:
# ML for quality of wine  GaussianNB

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report



model= GaussianNB()
x=total_wine.drop(columns=['quality_label', 'quality'])
y=total_wine['quality_label']
scale=MinMaxScaler()
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)
x_train_n=scale.fit_transform(x_train)
x_train_n=pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n=scale.fit_transform(x_test)
x_test_n=pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n,y_train)
predict=model.predict(x_test_n)
score=accuracy_score(y_test, predict)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, predict))
print(classification_report(y_test,predict))
cohen=cohen_kappa_score(y_test, predict)
print('cohen_kappa is: ', cohen)

accuracy is:  0.5558974358974359
Confusion matrix:
[[  1  10  47]
 [  0 112 623]
 [ 19 167 971]]
              precision    recall  f1-score   support

           0       0.05      0.02      0.03        58
           1       0.39      0.15      0.22       735
           2       0.59      0.84      0.69      1157

    accuracy                           0.56      1950
   macro avg       0.34      0.34      0.31      1950
weighted avg       0.50      0.56      0.50      1950

cohen_kappa is:  0.0009394848688508706


In [143]:
# ML for quality of wine  KNeighborsClassifier

from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report



model= KNeighborsClassifier()
x=total_wine.drop(columns=['quality_label', 'quality'])
y=total_wine['quality_label']
scale=MinMaxScaler()
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)
x_train_n=scale.fit_transform(x_train)
x_train_n=pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n=scale.fit_transform(x_test)
x_test_n=pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n,y_train)
predict=model.predict(x_test_n)
score=accuracy_score(y_test, predict)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, predict))
print(classification_report(y_test,predict))
cohen=cohen_kappa_score(y_test, predict)
print('cohen_kappa is: ', cohen)

accuracy is:  0.6225641025641026
Confusion matrix:
[[  2   9  47]
 [  4 434 297]
 [  7 372 778]]
              precision    recall  f1-score   support

           0       0.15      0.03      0.06        58
           1       0.53      0.59      0.56       735
           2       0.69      0.67      0.68      1157

    accuracy                           0.62      1950
   macro avg       0.46      0.43      0.43      1950
weighted avg       0.62      0.62      0.62      1950

cohen_kappa is:  0.24644289226895133


/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [144]:
# ML for quality of wine  support vector machine

from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report



model= SVC()
x=total_wine.drop(columns=['quality_label', 'quality'])
y=total_wine['quality_label']
scale=MinMaxScaler()
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)
x_train_n=scale.fit_transform(x_train)
x_train_n=pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n=scale.fit_transform(x_test)
x_test_n=pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n,y_train)
predict=model.predict(x_test_n)
score=accuracy_score(y_test, predict)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, predict))
print(classification_report(y_test,predict))
cohen=cohen_kappa_score(y_test, predict)
print('cohen_kappa is: ', cohen)

accuracy is:  0.6569230769230769
Confusion matrix:
[[  0   3  55]
 [  0 565 170]
 [  0 441 716]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        58
           1       0.56      0.77      0.65       735
           2       0.76      0.62      0.68      1157

    accuracy                           0.66      1950
   macro avg       0.44      0.46      0.44      1950
weighted avg       0.66      0.66      0.65      1950

cohen_kappa is:  0.3385131339027293


/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [145]:
# ML for quality of wine  adaboost

from sklearn.ensemble import AdaBoostClassifier

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report



model= AdaBoostClassifier()
x=total_wine.drop(columns=['quality_label', 'quality'])
y=total_wine['quality_label']
scale=MinMaxScaler()
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)
x_train_n=scale.fit_transform(x_train)
x_train_n=pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n=scale.fit_transform(x_test)
x_test_n=pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n,y_train)
predict=model.predict(x_test_n)
score=accuracy_score(y_test, predict)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, predict))
print(classification_report(y_test,predict))
cohen=cohen_kappa_score(y_test, predict)
print('cohen_kappa is: ', cohen)

accuracy is:  0.6702564102564103
Confusion matrix:
[[  0   8  50]
 [  0 514 221]
 [  3 361 793]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        58
           1       0.58      0.70      0.64       735
           2       0.75      0.69      0.71      1157

    accuracy                           0.67      1950
   macro avg       0.44      0.46      0.45      1950
weighted avg       0.66      0.67      0.66      1950

cohen_kappa is:  0.3477253230940661
