In [44]:
# This is a program to predict the quality of wine (both red+ white wines). Here I remove outliers based on z score meth.
import pandas as pd
import numpy as np
white_wine=pd.read_csv('../../practice/winequality-white.csv', sep=';')
red_wine=pd.read_csv('../../practice/winequality-red.csv', sep=';')
white_wine.columns=white_wine.columns.str.replace(' ', '_')
red_wine.columns=red_wine.columns.str.replace(' ', '_')

In [45]:
# type of wines
red_wine['wine_type']=0
white_wine['wine_type']=1


In [46]:
# merge
total_wine=pd.concat([white_wine, red_wine])
total_wine=total_wine.set_index(np.arange(len(total_wine)))


In [47]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_train.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.24923076923076923
Confusion matrix:
[[ 443   72]
 [1392   43]]
              precision    recall  f1-score   support

           0       0.24      0.86      0.38       515
           1       0.37      0.03      0.06      1435

    accuracy                           0.25      1950
   macro avg       0.31      0.45      0.22      1950
weighted avg       0.34      0.25      0.14      1950

cohen_kappa is:  -0.0602982413786699


In [75]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9317948717948717
Confusion matrix:
[[ 322  132]
 [   1 1495]]
              precision    recall  f1-score   support

           0       1.00      0.71      0.83       454
           1       0.92      1.00      0.96      1496

    accuracy                           0.93      1950
   macro avg       0.96      0.85      0.89      1950
weighted avg       0.94      0.93      0.93      1950

cohen_kappa is:  0.7877426820944359


In [78]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9030769230769231
Confusion matrix:
[[ 441   20]
 [ 169 1320]]
              precision    recall  f1-score   support

           0       0.72      0.96      0.82       461
           1       0.99      0.89      0.93      1489

    accuracy                           0.90      1950
   macro avg       0.85      0.92      0.88      1950
weighted avg       0.92      0.90      0.91      1950

cohen_kappa is:  0.7584909864157323


In [55]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9825641025641025
Confusion matrix:
[[ 479    4]
 [  30 1437]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       483
           1       1.00      0.98      0.99      1467

    accuracy                           0.98      1950
   macro avg       0.97      0.99      0.98      1950
weighted avg       0.98      0.98      0.98      1950

cohen_kappa is:  0.9540446910181284


In [85]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model=LinearDiscriminantAnalysis()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.45794871794871794
Confusion matrix:
[[ 500    2]
 [1055  393]]
              precision    recall  f1-score   support

           0       0.32      1.00      0.49       502
           1       0.99      0.27      0.43      1448

    accuracy                           0.46      1950
   macro avg       0.66      0.63      0.46      1950
weighted avg       0.82      0.46      0.44      1950

cohen_kappa is:  0.15869024829280842


In [87]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.7564102564102564
Confusion matrix:
[[  56  429]
 [  46 1419]]
              precision    recall  f1-score   support

           0       0.55      0.12      0.19       485
           1       0.77      0.97      0.86      1465

    accuracy                           0.76      1950
   macro avg       0.66      0.54      0.52      1950
weighted avg       0.71      0.76      0.69      1950

cohen_kappa is:  0.1142381731072667


In [69]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9856410256410256
Confusion matrix:
[[ 482    5]
 [  23 1440]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       487
           1       1.00      0.98      0.99      1463

    accuracy                           0.99      1950
   macro avg       0.98      0.99      0.98      1950
weighted avg       0.99      0.99      0.99      1950

cohen_kappa is:  0.9621498339722571


/Users/marziehbaes/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [89]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
model=SVC()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.8953846153846153
Confusion matrix:
[[ 264  204]
 [   0 1482]]
              precision    recall  f1-score   support

           0       1.00      0.56      0.72       468
           1       0.88      1.00      0.94      1482

    accuracy                           0.90      1950
   macro avg       0.94      0.78      0.83      1950
weighted avg       0.91      0.90      0.88      1950

cohen_kappa is:  0.6629659000793021


In [95]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier()
x=total_wine.drop(columns='wine_type')
y=total_wine['wine_type']
x_train,x_test,y_train, y_test=train_test_split(x,y, test_size=0.3)
scale=MinMaxScaler()
x_train_n= scale.fit_transform(x_train)
x_train_n= pd.DataFrame(x_train_n, columns=x_train.columns)
x_test_n= scale.fit_transform(x_test)
x_test_n= pd.DataFrame(x_test_n, columns=x_test.columns)
model.fit(x_train_n, y_train)
pred=model.predict(x_test_n)
score=accuracy_score(pred, y_test)
print('accuracy is: ', score)
print("Confusion matrix:")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))
cohen=cohen_kappa_score(y_test, pred)
print('cohen_kappa is: ', cohen)

accuracy is:  0.9123076923076923
Confusion matrix:
[[ 497   26]
 [ 145 1282]]
              precision    recall  f1-score   support

           0       0.77      0.95      0.85       523
           1       0.98      0.90      0.94      1427

    accuracy                           0.91      1950
   macro avg       0.88      0.92      0.90      1950
weighted avg       0.92      0.91      0.91      1950

cohen_kappa is:  0.791622141483223
